return {
	[1] = function (player:Player)
		print("Reward")
	end,
	[2] = function (player:Player)
		print("Reward")
	end,
	[3] = function (player:Player)
		print("Reward")
	end,
	[4] = function (player:Player)
		print("Reward")
	end,
	[5] = function (player:Player)
		print("Reward")
	end,
	[6] = function (player:Player)
		print("Reward")
	end,
	[7] = function (player:Player)
		print("Reward")
	end,
}