return {
	[1] = function (player:Player)
		print("Reward")
	end,
	[2] = function (player:Player)
		print("Reward")
	end,
	[3] = function (player:Player)
		print("Reward")
	end,
	[4] = function (player:Player)
		print("Reward")
	end,
	[5] = function (player:Player)
		print("Reward")
	end,
	[6] = function (player:Player)
		print("Reward")
	end,
	[7] = function (player:Player)
		print("Reward")
	end,
	[8] = function (player:Player)
		print("Reward")
	end,
	[9] = function (player:Player)
		print("Reward")
	end,
	[10] = function (player:Player)
		print("Reward")
	end,
	[11] = function (player:Player)
		print("Reward")
	end,
	[12] = function (player:Player)
		print("Reward")
	end,
	[13] = function (player:Player)
		print("Reward")
	end,
	[14] = function (player:Player)
		print("Reward")
	end,
	[15] = function (player:Player)
		print("Reward")
	end,
}