return {
	Config = {
		ResetDuration = 24 * 60 * 60, -- The time when the rewards will reset from the first time
	},
	Rewards = {
		[1] = {
			Duration = 5*60, -- Required time in order to unlock the reward (5 x 60 seconds = 5 minutes)
			Icon = 112943806732824, -- Icon ID for UI
		},
		[2] = {
			Duration = 15*60, -- Required time in order to unlock the reward (15 x 60 seconds = 15 minutes)
			Icon = 112943806732824,
		},
		[3] = {
			Duration = 30*60, -- Required time in order to unlock the reward (30 x 60 seconds = 30 minutes)
			Icon = 112943806732824,
		},
		[4] = {
			Duration = 60*60, -- Required time in order to unlock the reward (60 x 60 seconds = 1 hour)
			Icon = 112943806732824,
		},
		[5] = {
			Duration = 1.5*60*60, -- Required time in order to unlock the reward (1.5 x 60 x 60 seconds = 1.5 hours)
			Icon = 112943806732824,
		},
		[6] = {
			Duration = 2*60*60, -- Required time in order to unlock the reward (2 x 60 x 60 seconds = 2 hours)
			Icon = 112943806732824,
		},
		[7] = {
			Duration = 3*60*60, -- Required time in order to unlock the reward (3 x 60 x 60 seconds = 3 hours))
			Icon = 112943806732824,
		}
	}
}