-- What to promote on the right side UI

return {
	Packs = {
		["Starter Pack"] = 73167539394400, -- Change this to the Icon ID you want to use.
		["Secret Pack"] = 88132060004695, -- Change this to the Icon ID you want to use.
	},
	Passes = {
		["VIP"] = 122420734012429, -- Change this to the Icon ID you want to use.
		["Teleporter"] = 113198463459379, -- Change this to the Icon ID you want to use.
		["x2 Speed"] = 130304640405359 -- Change this to the Icon ID you want to use.
	},
	Products = {
		["100K Cash"] = 72195296200818, -- Change this to the Icon ID you want to use.
		["x5 Spins"] = 101212300915466, -- Change this to the Icon ID you want to use.
	}
}