return {
	NumberOfSpins = 5, -- Number of spins made before landing on selected segment
	FullSpinDuration = 4, -- The duration of spin
	StartingSpins = 1, -- The amount of spins have when they first join
	FreeSpinInterval = 5*60, -- The interval of free spin

	Rewards = {
		[1] = {
			Chance = 35, -- Percentage chance
			Icon = 110024503496390, -- Icon on UI
			Text = "100 Cash" -- Text on UI
		},
		[2] = {
			Chance = 30, -- Percentage chance
			Icon = 110024503496390, -- Icon on UI
			Text = "1K Cash" -- Text on UI
		},
		[3] = {
			Chance = 20, -- Percentage chance
			Icon = 110024503496390, -- Icon on UI
			Text = "10K Cash" -- Text on UI
		},
		[4] = {
			Chance = 10, -- Percentage chance
			Icon = 110024503496390, -- Icon on UI
			Text = "100K Cash" -- Text on UI
		},
		[5] = {
			Chance = 5, -- Percentage chance
			Icon = 110024503496390, -- Icon on UI
			Text = "150K Cash" -- Text on UI
		},
	}
}